sentinel monitor futures-master futures-redis-master 6379 2
sentinel auth-pass futures-master futures123
sentinel down-after-milliseconds futures-master 5000
sentinel failover-timeout futures-master 60000
sentinel parallel-syncs futures-master 1
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
port 26379
daemonize no
pidfile /var/run/redis-sentinel.pid
logfile ""
loglevel notice
