management:
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    nacos:
      enabled: false
    seata:
      enabled: false
    defaults:
      enabled: true
